# repo configurations for eIQ Machine Learning and GoPoint demo experience on iMX MPU platforms


# eIQ AI/ML components
repo:
  tim_vx:
    url:    https://github.com/nxp-imx/tim-vx-imx.git

  tvm:
    url:    https://github.com/nxp-imx/eiq-tvm-imx.git

  tflite:
    url:    https://github.com/nxp-imx/tensorflow-imx.git
    commit: 032564c4cbbc08a942553796f6365c412fc9863c

  tflite_vx_delegate:
    url:    https://github.com/nxp-imx/tflite-vx-delegate-imx.git
    commit: 4277fd719fc1849c3d448d77ac01af1a84dd3bf3

  tflite_ethosu_delegate:
    url:    https://github.com/nxp-imx/tflite-ethosu-delegate-imx.git
    commit: d23886fa1fb5dc9cb2aac00f4bd85d550d33fcdf

  ethosu_driver_stack:
    url:    https://github.com/nxp-imx/ethos-u-driver-stack-imx.git
    commit: a80c51d77c91f1a8266afc5d8056fb981de4b504

  ethosu_firmware:
    url:    https://github.com/nxp-imx/ethos-u-firmware.git
    commit: 3dbedc11bd2a4ba56af9fbe9d285b5bf13f1a088

  ethosu_vela:
    url:    https://github.com/nxp-imx/ethos-u-vela.git
    commit: 135efab5b1a30b08d4dcc075cb8bed2fadc28407

  nnstreamer:
    url:    https://github.com/nnstreamer/nnstreamer.git
    commit: 807060954acfdb6cec130559d00eef1af61457cf

  nnstreamer_edge:
    url:    https://github.com/nnstreamer/nnstreamer-edge.git
    commit: 2bf50d57f0f8d856ae38cf82b0a0f3746f46a08a

  nnshark:
    url:    https://github.com/nxp-imx/nnshark.git
    commit: 4ed66906b889e66a6458a1d2692790f64bf1c556

  ssat:
    url:    https://github.com/myungjoo/ssat.git
    commit: 1635168973

  eiq_examples:
    url:    https://github.com/nxp-imx/eiq-example.git

  pytorch:
    url:    https://github.com/nxp-imx/pytorch-release.git
    commit: 012e780225f891b90747592e254b2399d6ec07fb

  flatbuffers:
    url:    https://github.com/google/flatbuffers.git
    commit: 7d6d99c6befa63


# NXP GoPoint Demo Experience components
  imx_demo_experience:
    url:    https://github.com/nxp-imx-support/nxp-demo-experience.git

  imx_nnstreamer_examples:
    url:    https://github.com/nxp-imx/nxp-nnstreamer-examples.git
    commit: 1450073874cf6ef

  imx_demos_list:
    url:    https://github.com/nxp-imx-support/nxp-demo-experience-demos-list.git

  imx_smart_kitchen:
    url:    https://github.com/nxp-imx-support/smart-kitchen.git
    commit: 1f42aceae2e79f

  imx_smart_fitness:
    url:    https://github.com/nxp-imx-support/imx-smart-fitness.git
    commit: 5ac9a93c6c651e
