# [general]
machine=imx8mm-var-dart

MACHINE_LIST="imx8mm-var-som imx8mm-var-dart"

KERNEL_DEVICETREE=" \
	freescale/imx8mm-var-dart-1.x-dt8mcustomboard.dtb \
	freescale/imx8mm-var-dart-1.x-dt8mcustomboard-m4.dtb \
	freescale/imx8mm-var-dart-dt8mcustomboard.dtb \
	freescale/imx8mm-var-dart-dt8mcustomboard-m4.dtb \
	freescale/imx8mm-var-dart-wbe-dt8mcustomboard.dtb \
	freescale/imx8mm-var-dart-wbe-dt8mcustomboard-m4.dtb \
	freescale/imx8mm-var-som-1.x-symphony.dtb \
	freescale/imx8mm-var-som-1.x-symphony-1.x.dtb \
	freescale/imx8mm-var-som-1.x-symphony-m4.dtb \
	freescale/imx8mm-var-som-1.x-symphony-1.x-m4.dtb \
	freescale/imx8mm-var-som-symphony.dtb \
	freescale/imx8mm-var-som-symphony-1.x.dtb \
	freescale/imx8mm-var-som-symphony-m4.dtb \
	freescale/imx8mm-var-som-symphony-1.x-m4.dtb \
	freescale/imx8mm-var-som-wbe-symphony.dtb \
	freescale/imx8mm-var-som-wbe-symphony-1.x.dtb \
	freescale/imx8mm-var-som-wbe-symphony-m4.dtb \
	freescale/imx8mm-var-som-wbe-symphony-1.x-m4.dtb \
"

UBOOT_CONFIG="imx8mm_var_dart_defconfig"

IMX_MKIMAGE_DTBS="imx8mm-var-dart-dt8mcustomboard.dtb imx8mm-var-som-symphony.dtb"
IMX_MKIMAGE_TARGET="flash_lpddr4_ddr4_evk"
IMX_MKIMAGE_PATCHES=" \
    0001-iMX8M-soc.mak-use-native-mkimage-from-sysroot.patch \
    0001-iMX8M-soc-allow-dtb-override.patch \
    0002-iMX8M-soc-change-padding-of-DDR4-and-LPDDR4-DMEM-fir.patch \
    0001-iMX8M-soc-imx8mm-move-TEE_LOAD_ADDR-to-512mb-memory-.patch \
    0003-iMX8M-soc-add-variscite-imx8mm-support.patch \
"

# BOARD_VARIANTS="lpddr4 ddr4"

COMPOSITE_IMG1_FILE_sd="bsp/imx-mkimage/imx8mm-var-dart/flash.bin"
FLASH_BIN="$DEFAULT_OUT_PATH/${COMPOSITE_IMG1_FILE_sd}"
GENIMAGE_CFG="$FBDIR/configs/board/common/var-imx-sd-genconfig.conf"

# offset 33k
DISK_BOOTLOADER_OFFSET="33792"

# freeRTOS board target
CM_BOARD="dart_mx8mm"

# Recovery SD Card Configuration
INSTALL_DEBIAN_SCRIPT="https://raw.githubusercontent.com/varigit/meta-variscite-sdk-imx/037a5ce07d271ddb7d6f8389778816ef4e877c32/scripts/var_mk_yocto_sdcard/variscite_scripts/mx8_install_yocto.sh"
INSTALL_DEBIAN_ECHOS="https://raw.githubusercontent.com/varigit/meta-variscite-sdk-imx/037a5ce07d271ddb7d6f8389778816ef4e877c32/scripts/var_mk_yocto_sdcard/variscite_scripts/echos.sh"
INSTALL_DEBIAN_TARGET_BOOT="imx-boot-sd.bin"
INSTALL_DEBIAN_TARGET_ROOTFS="rootfs.tar.zst"
