# [general]
machine=imx8mq-var-dart

MACHINE_LIST="imx8mq-var-dart"

KERNEL_DEVICETREE=" \
	freescale/imx8mq-var-dart-dt8mcustomboard-m4-sd-hdmi.dtb \
	freescale/imx8mq-var-dart-dt8mcustomboard-m4-sd-lvds.dtb \
	freescale/imx8mq-var-dart-dt8mcustomboard-m4-sd-lvds-hdmi.dtb \
	freescale/imx8mq-var-dart-dt8mcustomboard-m4-wifi-hdmi.dtb \
	freescale/imx8mq-var-dart-dt8mcustomboard-m4-wifi-lvds.dtb \
	freescale/imx8mq-var-dart-dt8mcustomboard-m4-wifi-lvds-hdmi.dtb \
	freescale/imx8mq-var-dart-dt8mcustomboard-sd-hdmi.dtb \
	freescale/imx8mq-var-dart-dt8mcustomboard-sd-lvds.dtb \
	freescale/imx8mq-var-dart-dt8mcustomboard-sd-lvds-hdmi.dtb \
	freescale/imx8mq-var-dart-dt8mcustomboard-wifi-hdmi.dtb \
	freescale/imx8mq-var-dart-dt8mcustomboard-wifi-lvds.dtb \
	freescale/imx8mq-var-dart-dt8mcustomboard-wifi-lvds-hdmi.dtb \
"

IW612_UTILS="false"

UBOOT_CONFIG="imx8mq_var_dart_defconfig"

# Disable G2D
ENABLE_G2D="false"

IMX_MKIMAGE_DTBS="imx8mq-var-dart-dt8mcustomboard.dtb"
IMX_MKIMAGE_TARGET="flash_evk"
IMX_MKIMAGE_PATCHES=" \
    0001-iMX8M-soc.mak-use-native-mkimage-from-sysroot.patch \
    0001-iMX8M-soc-allow-dtb-override.patch \
    0002-iMX8M-soc-change-padding-of-DDR4-and-LPDDR4-DMEM-fir.patch \
    0001-iMX8M-soc-imx8mm-move-TEE_LOAD_ADDR-to-512mb-memory-.patch \
    0003-iMX8M-soc-add-variscite-imx8mm-support.patch \
    0001-iMX8M-soc-imx8mq-move-TEE_LOAD_ADDR-to-512mb-memory.patch \
"

# BOARD_VARIANTS="lpddr4 ddr4"

COMPOSITE_IMG1_FILE_sd="bsp/imx-mkimage/imx8mq-var-dart/flash.bin"
FLASH_BIN="$DEFAULT_OUT_PATH/${COMPOSITE_IMG1_FILE_sd}"
GENIMAGE_CFG="$FBDIR/configs/board/common/var-imx-sd-genconfig.conf"

# offset 33k
DISK_BOOTLOADER_OFFSET="33792"

# freeRTOS board target
CM_BOARD="dart_mx8mq"

# Recovery SD Card Configuration
INSTALL_DEBIAN_SCRIPT="https://raw.githubusercontent.com/varigit/meta-variscite-sdk-imx/037a5ce07d271ddb7d6f8389778816ef4e877c32/scripts/var_mk_yocto_sdcard/variscite_scripts/mx8_install_yocto.sh"
INSTALL_DEBIAN_ECHOS="https://raw.githubusercontent.com/varigit/meta-variscite-sdk-imx/037a5ce07d271ddb7d6f8389778816ef4e877c32/scripts/var_mk_yocto_sdcard/variscite_scripts/echos.sh"
INSTALL_DEBIAN_TARGET_BOOT="imx-boot-sd.bin"
INSTALL_DEBIAN_TARGET_ROOTFS="rootfs.tar.zst"

export ROOTFS_POST_CMD='cd "$RFSDIR/boot" && ln -sf imx8mq-var-dart-dt8mcustomboard-sd-lvds.dtb imx8mq-var-dart-dt8mcustomboard.dtb'
