# [general]
machine=imx8qxp-var-som

MACHINE_LIST="imx8qxp-var-som"

KERNEL_DEVICETREE=" \
	freescale/imx8qxp-var-som-symphony-sd.dtb \
	freescale/imx8qxp-var-som-symphony-wifi.dtb \
	freescale/imx8qxp-var-som-symphony-wifi-m4.dtb \
	freescale/imx8qxp-var-som-symphony-sd-m4.dtb \
"

# Disable G2D
ENABLE_G2D="false"

# Disable iw612 support
IW612_UTILS="false"

UBOOT_CONFIG="imx8qxp_var_som_defconfig"

IMX_MKIMAGE_DTBS="imx8qxp-var-som-symphony.dtb"
IMX_MKIMAGE_TARGET="flash_spl"

COMPOSITE_IMG1_FILE_sd="bsp/imx-mkimage/imx8qxp-var-som/flash.bin"
FLASH_BIN="$DEFAULT_OUT_PATH/${COMPOSITE_IMG1_FILE_sd}"
GENIMAGE_CFG="$FBDIR/configs/board/common/var-imx-sd-genconfig.conf"

# offset 33k for imx8qxp A0, 32K for B0 and C0
DISK_BOOTLOADER_OFFSET="32768"

# freeRTOS board target
CM_BOARD="som_mx8qx"
CM_GCC="9-2020-q2-update"
FREERTOS_COMMIT=45139490c76b13e052db4ec7b50d70faac2a7a5f
CM_DEMOS_DISABLE_CACHE="demo_apps/disable_cache"
DISABLE_CACHE_PATCH=disable_cache_2.9.x.patch

# SOC revision
SOC_REV="C0"

# Recovery SD Card Configuration
INSTALL_DEBIAN_SCRIPT="https://raw.githubusercontent.com/varigit/meta-variscite-sdk-imx/037a5ce07d271ddb7d6f8389778816ef4e877c32/scripts/var_mk_yocto_sdcard/variscite_scripts/mx8_install_yocto.sh"
INSTALL_DEBIAN_ECHOS="https://raw.githubusercontent.com/varigit/meta-variscite-sdk-imx/037a5ce07d271ddb7d6f8389778816ef4e877c32/scripts/var_mk_yocto_sdcard/variscite_scripts/echos.sh"
INSTALL_DEBIAN_TARGET_BOOT="imx-boot-sd.bin"
INSTALL_DEBIAN_TARGET_ROOTFS="rootfs.tar.zst"

export ROOTFS_POST_CMD=' \
	cd "$RFSDIR/boot" && \
	ln -sf imx8qxp-var-som-symphony-sd.dtb imx8qxp-var-som-symphony.dtb \
'
