# [general]
machine=imx8qm-var-som

MACHINE_LIST="imx8qm-var-som imx8qm-var-spear"

KERNEL_DEVICETREE=" \
	freescale/imx8qm-var-som-symphony-dp.dtb \
	freescale/imx8qm-var-som-symphony-hdmi.dtb \
	freescale/imx8qm-var-som-symphony-lvds.dtb \
	freescale/imx8qm-var-som-symphony-dp-m4.dtb \
	freescale/imx8qm-var-som-symphony-hdmi-m4.dtb \
	freescale/imx8qm-var-som-symphony-lvds-m4.dtb \
	freescale/imx8qm-var-som-symphony-1.x-dp.dtb \
	freescale/imx8qm-var-som-symphony-1.x-hdmi.dtb \
	freescale/imx8qm-var-som-symphony-1.x-lvds.dtb \
	freescale/imx8qm-var-som-symphony-1.x-dp-m4.dtb \
	freescale/imx8qm-var-som-symphony-1.x-hdmi-m4.dtb \
	freescale/imx8qm-var-som-symphony-1.x-lvds-m4.dtb \
	freescale/imx8qm-var-spear-sp8customboard-dp.dtb \
	freescale/imx8qm-var-spear-sp8customboard-hdmi.dtb \
	freescale/imx8qm-var-spear-sp8customboard-lvds.dtb \
	freescale/imx8qm-var-spear-sp8customboard-dp-m4.dtb \
	freescale/imx8qm-var-spear-sp8customboard-hdmi-m4.dtb \
	freescale/imx8qm-var-spear-sp8customboard-lvds-m4.dtb \
"

# Disable G2D
ENABLE_G2D="false"

# Disable iw612 support
IW612_UTILS="false"

UBOOT_CONFIG="imx8qm_var_som_defconfig"

IMX_MKIMAGE_DTBS="imx8qm-var-som-symphony.dtb imx8qm-var-spear-sp8customboard.dtb"
IMX_MKIMAGE_TARGET="flash_spl"

COMPOSITE_IMG1_FILE_sd="bsp/imx-mkimage/imx8qm-var-som/flash.bin"
FLASH_BIN="$DEFAULT_OUT_PATH/${COMPOSITE_IMG1_FILE_sd}"
GENIMAGE_CFG="$FBDIR/configs/board/common/var-imx-sd-genconfig.conf"

SOC_REV="B0"

DISK_BOOTLOADER_OFFSET="32768"

# freeRTOS board target
CM_BOARD="som_mx8qm"
CM_GCC="9-2020-q2-update"
FREERTOS_COMMIT=45139490c76b13e052db4ec7b50d70faac2a7a5f
CM_DEMOS_DISABLE_CACHE="demo_apps/disable_cache"
DISABLE_CACHE_PATCH=disable_cache_2.9.x.patch

# Recovery SD Card Configuration
INSTALL_DEBIAN_TARGET_BOOT="imx-boot-sd.bin"
INSTALL_DEBIAN_TARGET_ROOTFS="rootfs.tar.zst"

export ROOTFS_POST_CMD=' \
	cd "$RFSDIR/boot" && \
	ln -sf imx8qm-var-som-symphony-lvds-m4.dtb imx8qm-var-som-symphony.dtb && \
	ln -sf imx8qm-var-spear-sp8customboard-lvds-m4.dtb imx8qm-var-spear-sp8customboard.dtb \
'
