# [general]
machine=imx93-var-som

MACHINE_LIST="imx93-var-som imx93-var-dart"

KERNEL_DEVICETREE=" \
  freescale/imx93-var-som-symphony.dtb \
  freescale/imx93-var-som-symphony-ld.dtb \
  freescale/imx93-var-som-symphony-m33.dtb \
  freescale/imx93-var-som-wbe-symphony.dtb \
  freescale/imx93-var-som-wbe-symphony-ld.dtb \
  freescale/imx93-var-som-symphony-1.x.dtb \
  freescale/imx93-var-som-symphony-1.x-ld.dtb \
  freescale/imx93-var-som-symphony-1.x-m33.dtb \
  freescale/imx93-var-som-wbe-symphony-1.x.dtb \
  freescale/imx93-var-som-wbe-symphony-1.x-ld.dtb \
  freescale/imx93-var-dart-dt8mcustomboard.dtb \
  freescale/imx93-var-dart-dt8mcustomboard-ld.dtb \
  freescale/imx93-var-dart-dt8mcustomboard-m33.dtb \
  freescale/imx93-var-dart-sonata.dtb \
  freescale/imx93-var-dart-sonata-ld.dtb \
  freescale/imx93-var-dart-sonata-m33.dtb \
  freescale/imx93-var-dart-wbe-sonata.dtb \
  freescale/imx93-var-dart-wbe-sonata-ld.dtb \
"

# Disable G2D
ENABLE_G2D="false"
WESTON_RENDER="pixman"

UBOOT_CONFIG="imx93_var_som_defconfig"

IMX_MKIMAGE_DTBS="imx93-var-som-symphony.dtb"
IMX_MKIMAGE_TARGET="flash_singleboot"
IMX_MKIMAGE_PATCHES="0004-iMX93-soc-change-padding-of-LPDDR4-DMEM-firmware.patch"

COMPOSITE_IMG1_FILE_sd="bsp/imx-mkimage/${machine}/flash.bin"
FLASH_BIN="$DEFAULT_OUT_PATH/${COMPOSITE_IMG1_FILE_sd}"
GENIMAGE_CFG="$FBDIR/configs/board/common/var-imx-sd-genconfig.conf"

# Disable bcm43xx support
BCM43XX_UTILS="false"

# offset 32k
DISK_BOOTLOADER_OFFSET="32768"

# freeRTOS
CM_BOARD="som_mx93"
CM_GCC="12.2.rel1"
FREERTOS_COMMIT=76e6b345d782abc2b8a17cdf40d027bdf68fa44d
CM_BUILD_TARGETS="debug release"
DEMO_LIST="multicore_examples/rpmsg_lite_str_echo_rtos multicore_examples/rpmsg_lite_pingpong_rtos/linux_remote demo_apps/hello_world demo_apps/ethosu_apps_rpmsg"

# Recovery SD Card Configuration
INSTALL_DEBIAN_SCRIPT="https://raw.githubusercontent.com/varigit/meta-variscite-sdk-imx/037a5ce07d271ddb7d6f8389778816ef4e877c32/scripts/var_mk_yocto_sdcard/variscite_scripts/mx8_install_yocto.sh"
INSTALL_DEBIAN_ECHOS="https://raw.githubusercontent.com/varigit/meta-variscite-sdk-imx/037a5ce07d271ddb7d6f8389778816ef4e877c32/scripts/var_mk_yocto_sdcard/variscite_scripts/echos.sh"
INSTALL_DEBIAN_TARGET_BOOT="imx-boot-sd.bin"
INSTALL_DEBIAN_TARGET_ROOTFS="rootfs.tar.zst"
