# [general]
machine=imx91-var-som

MACHINE_LIST="imx91-var-som imx91-var-dart"

KERNEL_DEVICETREE=" \
	freescale/imx91-var-som-symphony.dtb \
	freescale/imx91-var-dart-dt8mcustomboard.dtb \
	freescale/imx91-var-dart-sonata.dtb \
	freescale/imx91-var-som-symphony-ld.dtb \
	freescale/imx91-var-dart-dt8mcustomboard-ld.dtb \
	freescale/imx91-var-dart-sonata-ld.dtb \
"

# Disable FreeRTOS support
FREERTOS_SUPPORT="false"

# Disable System Controller Firmware
SCFW_SUPPORT="false"

# Disable G2D
ENABLE_G2D="false"
WESTON_RENDER="pixman"

CORTEXM_TOOLCHAIN_SUPPORT="false"

UBOOT_CONFIG="imx91_var_som_defconfig"

IMX_MKIMAGE_DTBS="imx91-var-som-symphony.dtb"
IMX_MKIMAGE_TARGET="flash_singleboot"

COMPOSITE_IMG1_FILE_sd="bsp/imx-mkimage/${machine}/flash.bin"
FLASH_BIN="$DEFAULT_OUT_PATH/${COMPOSITE_IMG1_FILE_sd}"
GENIMAGE_CFG="$FBDIR/configs/board/common/var-imx-sd-genconfig.conf"

# Disable bcm43xx support
BCM43XX_UTILS="false"

# offset 32k
DISK_BOOTLOADER_OFFSET="32768"

# Recovery SD Card Configuration
INSTALL_DEBIAN_SCRIPT="https://raw.githubusercontent.com/varigit/meta-variscite-sdk-imx/037a5ce07d271ddb7d6f8389778816ef4e877c32/scripts/var_mk_yocto_sdcard/variscite_scripts/mx8_install_yocto.sh"
INSTALL_DEBIAN_ECHOS="https://raw.githubusercontent.com/varigit/meta-variscite-sdk-imx/037a5ce07d271ddb7d6f8389778816ef4e877c32/scripts/var_mk_yocto_sdcard/variscite_scripts/echos.sh"
INSTALL_DEBIAN_TARGET_BOOT="imx-boot-sd.bin"
INSTALL_DEBIAN_TARGET_ROOTFS="rootfs.tar.zst"
